# Generated by Django 4.2.15 on 2024-08-26 20:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('ingredients', models.JSONField(validators=[api.models.validate_ingredients])),
                ('description', models.TextField()),
            ],
        ),
    ]
